---
- name: Install and start nginx
  hosts: groupe1, groupe2
  tasks:
    - name: "vérifier la variable"
      debug:
        msg: "{{ var1 }}"
    - name: install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
      become: yes
    - name: start nginx
      ansible.builtin.service:
        name: "{{ var1 }}"
        state: started
      become: yes
    - name: create a test folder
      ansible.builtin.file:
        path: /tmp/oui/non/
        state: directory
        mode: 0777
    - name: "copy a file"
      copy:
        src: /ansfile/groupe1/oui.txt
        dest: /tmp/oui/non/
        mode: 0777
        force: True
      tags: copy
    - name: "copy folders"
      copy:
        src: /ansfile/
        dest: /tmp/oui/non/
        mode: 0777
        force: True
      tags: copy
